spring:
  config:
    activate:
      on-profile: local
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          #driver-class-name: com.mysql.cj.jdbc.Driver
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://192.168.164.128:3306/base_project?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&zeroDateTimeBehavior=convertToNull&autoReconnect=true
          username: root
          password: 123456